- name: enable nodejs module
  ansible.builtin.shell: dnf module disable nodejs -y

- name: enable nodejs module
  ansible.builtin.shell: dnf module enable nodejs:20 -y

- name: Install nodejs package
  ansible.builtin.dnf:
    name: nodejs
    state: latest

- name: Add application user
  ansible.builtin.user:
    name: expense

- name: clean the code
  ansible.builtin.file:
    path: /app
    state: absent

- name: Make a directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download frontend
  ansible.builtin.get_url:
    url: https://expense-artifacts.s3.amazonaws.com/expense-backend-v2.zip
    dest: /tmp/backend.zip

- name: Unarchive frontend
  ansible.builtin.unarchive:
    src: /tmp/backend.zip
    dest: /app
    remote_src: yes

- name: Install npm package
  community.general.npm:
    name: npm
    path: /app
    state: present

- name: Copy backend service
  ansible.builtin.template:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: Start Mysql-server service
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: backend

- name: restart backend service
  ansible.builtin.service:
     name: backend
     state: restarted
      enabled: yes

- name: Install nginx package
   ansible.builtin.dnf:
      name: mysql
      state: latest





