- name: set prompt
  ansible.builtin.shell: set prompt sonarqube

- name: Add sonarqube user
  ansible.builtin.user:
    name: sonar

- name: Install Java
  ansible.builtin.dnf:
    name: java-17-openjdk
    state: installed

- name: create sonarqube directory
  ansible.builtin.file:
    path: /opt/sonarqube
    owner: sonar
    group: sonar

- name: Download sonarqube
  ansible.builtin.get_url:
    url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-10.5.1.90531.zip
    dest: /opt/sonarqube
    owner: sonar
    group: sonar

#- name: Download and unarchive sonarqube
#  ansible.builtin.unarchive:
#    src: /opt/sonarqube
#    dest: /opt/sonarqube
#    remote_src: yes
#  become_user: sonar
