- name: expense backend playbook
  hosts: localhost
  become: true
  tasks:
    - name: disable nodejs module
      ansible.builtin.shell: dnf module disable nodejs -y

    - name: enable nodejs module
      ansible.builtin.shell: dnf module enable nodejs:20 -y

    - name: Install nodejs package
      ansible.builtin.dnf:
        name: nodejs
        state: installed

