- name: expense backend playbook
  hosts: localhost
  become: true
  tasks:
    - name: disable nodejs module
      ansible.builtin.shell: dnf module disable nodejs -y

    - name: enable nodejs module
      ansible.builtin.shell: dnf module enable nodejs:20 -y

    - name: Install nodejs package
      ansible.builtin.dnf:
        name: nodejs
        state: installed

    - name: Add application user
      ansible.builtin.user:
        name: expense

    - name: clean the code
      ansible.builtin.file:
         path: /app
         state: absent

    - name: Make a drirectory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download frontend
      ansible.builtin.get_url:
        url: https://expense-artifacts.s3.amazonaws.com/expense-backend-v2.zip
        dest: /tmp/backend.zip

    - name: Unarchive frontend
      ansible.builtin.unarchive:
        src: /tmp/backend.zip
        dest: /app
        remote_src: yes

    - name: Install nodejs package
      community.general.npm:
        name: nodejs
        path: /app
        state: latest

