- name: get secrets from vault
  hosts: all
  tasks:
   - name: get vault common credentials
     ansible.builtin.lineinfile:
       path: secrets.json
       line: "{{ lookup('hashi_vault', 'secret=expense/data/ssh token={{vault_token}} url=https://54.83.181.116:8200 validate_certs=False')}}"
       create: yes




