- name: get secrets from vault
  hosts: all
  become: true
  tasks:
   - name: Ensure SELinux is set to enforcing mode
     ansible.builtin.lineinfile:
       path: secrets.json
       line: "{{ lookup('hashi_vault', 'secret=expense/data/ssh token={{vault_token}} url=https://54.83.181.116:8200 validate_certs=False')}}"
       create: yes

   - name: Ensure SELinux is set to enforcing mode
     ansible.builtin.lineinfile:
       path: app.json
       line: "{{ lookup('hashi_vault', 'secret={{ env }}/data/{{ component }} token={{vault_token}} url=https://54.83.181.116:8200 validate_certs=False')}}"
       create: yes


