- name: get secrets from vault
  hosts: localhost
  tasks:
   - name: get vault common ssh credentials
     ansible.builtin.lineinfile:
       path: secrets.json
       line: "{{ lookup('hashi_vault', 'secret=expense/data/ssh token={{vault_token}} url=https://54.242.214.124:8200 validate_certs=False')}}"
       create: yes

   - name: get vault expense credentials
     ansible.builtin.lineinfile:
       path: app.json
       line: "{{ lookup('hashi_vault', 'secret=expense-{{env}}/data/{{component}} token={{vault_token}} url=https://54.242.214.124:8200 validate_certs=False')}}"
       create: yes



