- name: get secrets from vault
  hosts: localhost
  tasks:
   - name: get vault common credentials
     ansible.builtin.lineinfile:
       path: secrets.json
       line: "{{ lookup('hashi_vault', 'secret=expense/data/ssh token=hvs.euEam4HUc3gK3ONTmkrZIofp url=https://54.242.214.124:8200 validate_certs=False')}}"
       create: yes




