- name: get secrets from vault
  hosts: all
  become: true
  tasks:
   - name: Ensure SELinux is set to enforcing mode
     ansible.builtin.lineinfile:
       path: secrets.json
       line: "{{ lookup('hashi_vault', 'secret=expense/data/ssh token={{vault_token}} url=https://vault-public.pdevops72.online:8200 validate_certs=False')}}"


