- name: Install nginx package
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: start nginx service
  ansible.builtin.systemd_service:
    name: nginx
    state: started

- name: Enabled nginx service
  ansible.builtin.service:
    name: nginx
    enabled: yes

- name: Import code commonly
  ansible.builtin.import_role:
    name: common
    tasks_from: pre-req.yml

- name: copy expense conf
  ansible.builtin.copy:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: restart nginx service
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes

- name: Import nginx newrelic
  ansible.builtin.import_role:
    name: newrelic
    tasks_from: relic_nginx