- name: make a runner directory
  ansible.builtin.file:
    path: /home/ec2-user/actions-runner
    state: directory
    owner: ec2-user
    group: ec2-user

- name: Download runner
  ansible.builtin.unarchive:
    src: https://github.com/actions/runner/releases/download/v2.317.0/actions-runner-linux-x64-2.317.0.tar.gz
    dest: /home/ec2-user/actions-runner
    remote_src: yes
  become_user: ec2-user
