- name: Install mysql server package
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: start and enable service
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: yes

- name: Get DB Info credentials
  community.mysql.mysql_info:
    login_user: root
    login_password: ExpenseApp@1
    login_host: 172.31.20.157
    filter: version
  register: mysql-connection-output

- name: Set Rootpassword
  ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1
