format_version: 10
pipelines:
  backend:
    group: expense
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-2ae7d73:
        git: https://github.com/devps23/expense-ansible.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      vault_token: "AES:BPk0TO+DrDPAkmsusuAdKA==:TDl9gEAGJBJCNR8tTYa1115kxa2Bc6cNvN0dEQjPH7I="
    stages:
    - DEV:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
          allow_only_on_success: false
        jobs:
          test-job:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - ansible.sh
                - backend
                - dev
                command: bash
                run_if: passed
