vault_token: "{{ lookup('ansible.builtin.env', 'vault_token') }}"
token: "{{ lookup('hashi_vault', 'secret=common/data/ci_secrets token={{ vault_token }} url=https://54.145.44.185:8200 validate_certs=False')}}"
