- name: set prompt
  ansible.builtin.shell: set-prompt jenkins

- name: copy jenkins repo
  ansible.builtin.template:
    src: jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Install fontconfig
  ansible.builtin.dnf:
    name: fontconfig
    state: installed

- name: Install java-17-openjdk
  ansible.builtin.dnf:
    name: java-17-openjdk
    state: installed

- name: Install jenkins
  ansible.builtin.dnf:
    name: jenkins
    state: installed

- name: Creates directory
  ansible.builtin.file:
    path: /var/lib/jenkins/init.groovy.d
    state: directory



- name: copy groovy file
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /var/lib/jenkins/init.groovy.d/{{ item }}
  loop:
    - 01-wizard.groovy
    - 02-admin-user.groovy
    - 03-plugins.groovy

- name: start jenkins service
  ansible.builtin.systemd_service:
    name: jenkins
    state: started
    enabled: yes
