- name: set prompt
  ansible.builtin.shell: sudo set-prompt jenkins

- name: copy jenkins repo
  ansible.builtin.template:
    src: jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Install fontconfig
  ansible.builtin.dnf:
    name: fontconfig
    state: installed

- name: Install java-17-openjdk
  ansible.builtin.dnf:
    name: java-17-openjdk
    state: installed

- name: Install jenkins
  ansible.builtin.dnf:
    name: jenkins
    state: installed

- name: start jenkins service
  ansible.builtin.systemd_service:
    name: jenkins
    state: started