- name: clean the code
  ansible.builtin.file:
    path: {{ app_loc }}
    state: absent

- name: Make a drirectory
  ansible.builtin.file:
    path: {{ app_loc }}
    state: directory

- name: Download frontend
  ansible.builtin.get_url:
    url: https://expense-artifacts.s3.amazonaws.com/expense-{{ component }}-v2.zip
    dest: /tmp/{{ component }}.zip

- name: Unarchive frontend
  ansible.builtin.unarchive:
    src: /tmp/{{ component }}.zip
    dest: {{ app_loc }}
    remote_src: yes

- name: copy expense conf
  ansible.builtin.copy:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

