- name: add vault repo file
  ansible.builtin.shell: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

- name: Install vault package
  ansible.buitlin.dnf:
    name: vault
    state: installed

- name: start vault service
  ansible.builtin.systemd_service:
    name: vault
    state: restarted
    enabled: true

- name: get vault credentials
  ansible.builtin.debug:
    msg: "{{ lookup('hashi_vault', 'secret=expense/data/demo token=hvs.tyEMRhd9Ms8lvUUU1ML0kYtp
     url=https://54.242.186.30:8200')}}"
